services:
  db:
    image: postgres:17 # Sử dụng phiên bản PostgreSQL ổn định
    container_name: ecommerce_postgress
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_URL: ${DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALGORITHM: ${ALGORITHM}
    depends_on:
      - db
    networks:
      - ecommerce-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Mapping cổng 3000 trên host với cổng 80 trong container
    depends_on:
      - backend
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
